version: "3.4"

services:
  postgres:
    container_name: nest_db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: nest
      POSTGRES_PASSWORD: nest

volumes:
  postgres_data: